name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run lint
        run: make lint
        continue-on-error: true

      - name: Build application
        run: make build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_SECRET_REGION }}

      - name: Update Lambda Function Configuration
        run: |
          aws lambda update-function-configuration \
            --function-name laba-it-devops-image-uploader \
            --environment "Variables={
              BOOKS_AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }},
              BOOKS_AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }},
              BOOKS_AWS_REGION=${{ secrets.AWS_SECRET_REGION }},
              BUCKET_NAME=laba-it-devops-image-bucket
            }"

      - name: Deploy to AWS Lambda
        run: aws lambda update-function-code --function-name laba-it-devops-image-uploader --zip-file fileb://app.zip
